"""
Config & Constants for Self-Generating GitHub Profile
======================================================

Central hub for all tunable parameters:
- Colors (Gojo's Hollow Purple palette)
- ASCII brightness ramp
- Image dimensions & animation timing
- File paths
- GitHub API settings
"""

import os
from pathlib import Path

# ============================================================================
# DIRECTORIES
# ============================================================================

BASE_DIR = Path(__file__).parent.parent  # repo root
SCRIPTS_DIR = BASE_DIR / "scripts"
ASSETS_DIR = BASE_DIR / "assets"
FONTS_DIR = ASSETS_DIR / "fonts"
PHOTOS_DIR = ASSETS_DIR / "photos"
TEMPLATES_DIR = ASSETS_DIR / "templates"
OUTPUT_DIR = BASE_DIR / "output"

# Ensure output dir exists
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================================
# FILE PATHS (Input & Output)
# ============================================================================

# Input
HEADSHOT_PATH = PHOTOS_DIR / "headshot.jpg"
README_TEMPLATE_PATH = TEMPLATES_DIR / "README_template.md"

# Fonts (WOFF2 subsets, generated by font_subsetter.sh)
FONT_RAMP_PATH = FONTS_DIR / "ramp.woff2"
FONT_HEADING_PATH = FONTS_DIR / "heading.woff2"
FONT_STATS_PATH = FONTS_DIR / "stats.woff2"

# Output SVGs (generated by GitHub Actions daily)
PORTRAIT_SVG_PATH = OUTPUT_DIR / "portrait.svg"
STATS_SVG_PATH = OUTPUT_DIR / "stats.svg"
STREAK_SVG_PATH = OUTPUT_DIR / "streak.svg"
LANGS_SVG_PATH = OUTPUT_DIR / "langs.svg"
YEAR_SVG_PATH = OUTPUT_DIR / "year.svg"

# Final README (committed to repo)
README_PATH = BASE_DIR / "README.md"

# ============================================================================
# COLOR PALETTE: Gojo's Hollow Purple
# ============================================================================

COLORS = {
    # Primary palette (Hollow Purple gradient)
    'red_top': '#FF0B3C',           # Crimson red accent (top)
    'purple_deep': '#7D0080',       # Deep purple (main portrait color)
    'blue_bottom': '#0033FF',       # Electric blue accent (bottom)
    'purple_mid': '#A020A0',        # Mid-tone purple (blend/stats)
    'purple_light': '#D77FD8',      # Light purple (highlights, strokes)
    
    # Background & text
    'bg_dark': '#0A0E27',           # Dark background (almost black)
    'text_white': '#FFFFFF',        # White text
    'text_gray': '#B0B0B0',         # Secondary text (dimmed)
    'text_dim': '#808080',          # Tertiary text (very dim)
}

# Specific uses
PORTRAIT_FILL_COLOR = COLORS['purple_deep']        # '#7D0080'
PORTRAIT_CURSOR_COLOR = COLORS['purple_light']     # '#D77FD8'
STATS_BAR_COLOR = COLORS['purple_mid']             # '#A020A0'
STATS_ACCENT_COLOR = COLORS['purple_light']        # '#D77FD8'
SPARKLINE_COLOR = COLORS['blue_bottom']            # '#0033FF'
HEADING_UNDERLINE_START = COLORS['red_top']        # '#FF0B3C'
HEADING_UNDERLINE_END = COLORS['blue_bottom']      # '#0033FF'

# ============================================================================
# ASCII BRIGHTNESS RAMP (13 levels)
# ============================================================================

# Character set from brightest to darkest
# Maps pixel brightness 0-255 → character from this ramp
ASCII_RAMP = ' .`:-=+*cs#%@'  # Space to @: 13 distinct levels

# Reverse map (for reference in code)
ASCII_RAMP_REVERSE = dict(zip(ASCII_RAMP, range(len(ASCII_RAMP))))

# Character-to-brightness (0.0-1.0)
CHAR_BRIGHTNESS = {
    ' ': 0.0,    # Brightest (highlights)
    '.': 0.08,
    '`': 0.15,
    ':': 0.23,
    '-': 0.31,
    '=': 0.38,
    '+': 0.46,
    '*': 0.54,
    'c': 0.62,
    's': 0.69,
    '#': 0.77,
    '%': 0.85,
    '@': 1.0,    # Darkest (shadows)
}

# ============================================================================
# PORTRAIT GENERATION
# ============================================================================

# ASCII output dimensions
PORTRAIT_COLUMNS = 90  # Width in characters
# Height is calculated: rows = cols * (photo_height / photo_width) * 0.48
# 0.48 = correction for monospace characters being ~2x taller than wide

# Font metrics
CHAR_WIDTH_EM = 0.600  # JetBrains Mono advance width (exact: 7.74px at 12.9pt)
FONT_SIZE_PX = 12.9
CHAR_WIDTH_PX = 7.74   # at FONT_SIZE_PX

# SVG rendering
PORTRAIT_SVG_VIEWBOX_WIDTH = 700   # Viewbox width for SVG container
PORTRAIT_SVG_DISPLAY_WIDTH_PX = 460  # Display width (rendering context)
PORTRAIT_FILL = PORTRAIT_FILL_COLOR
PORTRAIT_TEXT_ANCHOR = "middle"    # Text alignment in SVG

# ============================================================================
# TYPING ANIMATION (SMIL)
# ============================================================================

TYPING_ANIMATION_DELAY_ROWS = 0.09  # seconds between consecutive row starts
TYPING_ANIMATION_DURATION_PER_ROW = 0.09  # seconds to fully type one row
TYPING_CURSOR_WIDTH_CHARS = 1  # Width of animated cursor block
TYPING_CURSOR_OPACITY = 0.5  # Cursor transparency

# Calculated: 90 rows × 0.09s = ~8.1 seconds total animation
TOTAL_ANIMATION_TIME = PORTRAIT_COLUMNS * TYPING_ANIMATION_DELAY_ROWS

# ============================================================================
# GITHUB GRAPHQL API
# ============================================================================

GITHUB_API_ENDPOINT = "https://api.github.com/graphql"

# Contribution window
CONTRIBUTION_WINDOW_DAYS = 364  # One year minus 1 day (for week alignment)

# API uses the environment variable GITHUB_TOKEN
# (injected by GitHub Actions or set locally via .env)
# No need to store it in this file

# ============================================================================
# STATS GRAPHICS
# ============================================================================

# Bar chart dimensions
STATS_CHART_WIDTH_PX = 600
STATS_CHART_HEIGHT_PX = 300
STATS_BAR_HEIGHT_PX = 20
STATS_SPACING_PX = 4

# Streak display
STREAK_DISPLAY_WIDTH_PX = 400
STREAK_DISPLAY_HEIGHT_PX = 150

# Languages chart (horizontal bars)
LANGS_CHART_WIDTH_PX = 600
LANGS_CHART_HEIGHT_PX = 250
LANGS_MAX_DISPLAY = 5  # Top 5 languages only

# Year heatmap (365 days, ~1 char per day)
YEAR_CHART_WIDTH_PX = 500
YEAR_CHART_HEIGHT_PX = 80
YEAR_CELL_SIZE_PX = 2

# ============================================================================
# IMAGE PREPROCESSING
# ============================================================================

# Headshot preprocessing
HEADSHOT_TARGET_WIDTH_PX = 1200  # Recommended: 1200px+
HEADSHOT_QUALITY_JPG = 95  # JPEG quality for saved images

# Grayscale conversion method
# Options: 'luminosity' (standard), 'average', 'desaturation'
GRAYSCALE_METHOD = 'luminosity'  # Preserves brightness perception

# Optional: Background removal (rembg) — set to True if desired
USE_BACKGROUND_REMOVAL = True  # True = slower, removes background via ML
BACKGROUND_REMOVAL_MODEL = "u2net"  # or "u2netp", "girlremover", etc.

# ============================================================================
# SVG FONT EMBEDDING
# ============================================================================

# Font data (base64) will be embedded in each SVG for independence
# This avoids CORS issues — GitHub serves SVG as an image, can't fetch external fonts
EMBED_FONTS_IN_SVG = True

# Font subsets (generated by font_subsetter.sh)
FONT_SUBSETS = {
    'ramp': {
        'chars': ' .`:-=+*cs#%@',
        'weight': 'regular',
        'output': 'ramp.woff2',
    },
    'heading': {
        'chars': 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 .,;:!?()\'"—–-',
        'weight': 'regular',
        'output': 'heading.woff2',
    },
    'stats': {
        'chars': '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz% .,',
        'weight': 'regular',
        'output': 'stats.woff2',
    },
}

# ============================================================================
# README ASSEMBLY
# ============================================================================

# Line length control (hard-wrap to this many chars)
README_LINE_LENGTH = 76  # Prevents overflow on narrow screens

# Section ordering in README
README_SECTIONS = [
    'intro',
    'portrait',
    'stats',
    'languages',
    'year_heatmap',
    'featured_projects',
    'footer',
]

# ============================================================================
# GITHUB ACTIONS WORKFLOW
# ============================================================================

# Cron schedule for daily refresh
WORKFLOW_SCHEDULE_CRON = "17 5 * * *"  # 05:17 UTC every day
# (time chosen to avoid traffic spikes at :00 minutes)

# Commit message when stats change
WORKFLOW_COMMIT_MESSAGE = "stats: refresh"

# Only commit if these files change
WORKFLOW_WATCH_FILES = [
    'portrait.svg',
    'stats.svg',
    'streak.svg',
    'langs.svg',
    'year.svg',
    'README.md',
]

# ============================================================================
# LOGGING & DEBUG
# ============================================================================

LOG_LEVEL = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
LOG_FORMAT = "[%(levelname)s] %(message)s"

# Verbose output during local testing
VERBOSE = False  # Set to True for debugging

# ============================================================================
# VALIDATION
# ============================================================================

def validate_config():
    """Verify all critical paths and settings exist."""
    errors = []
    
    # Check directories exist or can be created
    for dir_path in [FONTS_DIR, PHOTOS_DIR, TEMPLATES_DIR, OUTPUT_DIR]:
        if not dir_path.exists():
            try:
                dir_path.mkdir(parents=True, exist_ok=True)
            except Exception as e:
                errors.append(f"Cannot create {dir_path}: {e}")
    
    # Warn if critical files missing
    if not HEADSHOT_PATH.exists():
        errors.append(f"Headshot not found: {HEADSHOT_PATH}")
    
    if not README_TEMPLATE_PATH.exists():
        errors.append(f"README template not found: {README_TEMPLATE_PATH}")
    
    # Check GitHub API endpoint
    if not GITHUB_API_ENDPOINT.startswith('https://'):
        errors.append(f"Invalid API endpoint: {GITHUB_API_ENDPOINT}")
    
    return errors

# ============================================================================
# UTILITIES
# ============================================================================

def get_char_for_brightness(brightness: float) -> str:
    """
    Map a brightness value (0.0-1.0) to the ASCII ramp character.
    
    Args:
        brightness: 0.0 (white/bright) to 1.0 (black/dark)
    
    Returns:
        Character from ASCII_RAMP matching brightness level
    """
    if not 0.0 <= brightness <= 1.0:
        raise ValueError(f"Brightness must be 0.0-1.0, got {brightness}")
    
    # Map to index in ramp (0-12)
    index = int(brightness * (len(ASCII_RAMP) - 1))
    return ASCII_RAMP[index]

def load_font_base64(font_path: Path) -> str:
    """Load a WOFF2 font file and return as base64 data URI."""
    import base64
    
    if not font_path.exists():
        raise FileNotFoundError(f"Font file not found: {font_path}")
    
    with open(font_path, 'rb') as f:
        font_bytes = f.read()
    
    b64 = base64.b64encode(font_bytes).decode('ascii')
    return f"data:font/woff2;base64,{b64}"

# ============================================================================
# ENVIRONMENT
# ============================================================================

# GitHub Actions sets these automatically
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN', None)
GITHUB_LOGIN = os.getenv('GH_LOGIN', None)  # Set in workflow as github.repository_owner

# Local override for testing
GITHUB_USERNAME = GITHUB_LOGIN or 'EgoisticPotato'

# ============================================================================
if __name__ == "__main__":
    # Run validation if executed directly
    errors = validate_config()
    if errors:
        print("❌ Config validation errors:")
        for error in errors:
            print(f"  - {error}")
    else:
        print("✅ Config validation passed")
        print(f"\nProfile will generate in: {OUTPUT_DIR}")
        print(f"Total animation time: {TOTAL_ANIMATION_TIME:.1f}s")
